### ISSUE TITLE
Question: Trying to replace LuongAttention with dot_prod_attention.

### ISSUE THREAD

**Issue by AviVarma** [xiye17/torchASN#2]
I am trying to understand the scaled dot product implementation provided in `nn.utils.py` on `line 16`. why are you adding a batch_size dimension and what is hidden_size? can you describe the function's input parameters and outputs in more detail please.

**Comment by xiye17** [comment]
oh, this is actually not used in my code. (I just include this util from TranX as much of the framework is borrowed from there).
But if you want to use this. I think h_t is the current decoder hidden states, src_encoding is the encoder hidden status (2 * hidden_size since bi-directional is the default), src_encoding_att_linear should be the vectors for computing attention scores (I guess Authors of TranX may use a linear layer to reduce the 2*hidden_sizee to hidden_size). 

I think you may refer to the TranX repo to find some usage of this function.

**Comment by AviVarma** [comment]
Within your LuongAttention implementation I'm guessing you are using the Luong Location-Base attention? can you explain you're implementtion please? Thanks again for all the help!

I'm essentially trying to implement a simple version of the scaled dot product attention onto the decoder. This is essentially the Luong dot product attention.

**Comment by xiye17** [comment]
My implementation is refered as general type attention in the paper $$h^T_t W h_s$$
To  implement dot attention, you might need to do $$dot_prod(h_t, W h_s) when h_s is of (2 * hidden_size) [reducing h_s so they have the same size and then you can do dot production].
